[project]
name = "letterboxd-wrapped"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.3.4",
    "polars>=1.17.1",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
